// Generated by gencpp from file assign/myMess.msg
// DO NOT EDIT!


#ifndef ASSIGN_MESSAGE_MYMESS_H
#define ASSIGN_MESSAGE_MYMESS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assign
{
template <class ContainerAllocator>
struct myMess_
{
  typedef myMess_<ContainerAllocator> Type;

  myMess_()
    : angle1(0.0)
    , angle2(0.0)
    , angle3(0.0)
    , angle4(0.0)  {
    }
  myMess_(const ContainerAllocator& _alloc)
    : angle1(0.0)
    , angle2(0.0)
    , angle3(0.0)
    , angle4(0.0)  {
  (void)_alloc;
    }



   typedef float _angle1_type;
  _angle1_type angle1;

   typedef float _angle2_type;
  _angle2_type angle2;

   typedef float _angle3_type;
  _angle3_type angle3;

   typedef float _angle4_type;
  _angle4_type angle4;





  typedef boost::shared_ptr< ::assign::myMess_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assign::myMess_<ContainerAllocator> const> ConstPtr;

}; // struct myMess_

typedef ::assign::myMess_<std::allocator<void> > myMess;

typedef boost::shared_ptr< ::assign::myMess > myMessPtr;
typedef boost::shared_ptr< ::assign::myMess const> myMessConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assign::myMess_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assign::myMess_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assign::myMess_<ContainerAllocator1> & lhs, const ::assign::myMess_<ContainerAllocator2> & rhs)
{
  return lhs.angle1 == rhs.angle1 &&
    lhs.angle2 == rhs.angle2 &&
    lhs.angle3 == rhs.angle3 &&
    lhs.angle4 == rhs.angle4;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assign::myMess_<ContainerAllocator1> & lhs, const ::assign::myMess_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assign

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assign::myMess_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assign::myMess_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assign::myMess_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assign::myMess_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assign::myMess_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assign::myMess_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assign::myMess_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6dbee5393cf7cdd1b23eb5beb5d9c6de";
  }

  static const char* value(const ::assign::myMess_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6dbee5393cf7cdd1ULL;
  static const uint64_t static_value2 = 0xb23eb5beb5d9c6deULL;
};

template<class ContainerAllocator>
struct DataType< ::assign::myMess_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assign/myMess";
  }

  static const char* value(const ::assign::myMess_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assign::myMess_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 angle1\n"
"float32 angle2\n"
"float32 angle3\n"
"float32 angle4\n"
;
  }

  static const char* value(const ::assign::myMess_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assign::myMess_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle1);
      stream.next(m.angle2);
      stream.next(m.angle3);
      stream.next(m.angle4);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct myMess_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assign::myMess_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assign::myMess_<ContainerAllocator>& v)
  {
    s << indent << "angle1: ";
    Printer<float>::stream(s, indent + "  ", v.angle1);
    s << indent << "angle2: ";
    Printer<float>::stream(s, indent + "  ", v.angle2);
    s << indent << "angle3: ";
    Printer<float>::stream(s, indent + "  ", v.angle3);
    s << indent << "angle4: ";
    Printer<float>::stream(s, indent + "  ", v.angle4);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGN_MESSAGE_MYMESS_H
