// Generated by gencpp from file exam/mySer.msg
// DO NOT EDIT!


#ifndef EXAM_MESSAGE_MYSER_H
#define EXAM_MESSAGE_MYSER_H

#include <ros/service_traits.h>


#include <exam/mySerRequest.h>
#include <exam/mySerResponse.h>


namespace exam
{

struct mySer
{

typedef mySerRequest Request;
typedef mySerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct mySer
} // namespace exam


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::exam::mySer > {
  static const char* value()
  {
    return "0d48ea28d372a544a46a655505887e00";
  }

  static const char* value(const ::exam::mySer&) { return value(); }
};

template<>
struct DataType< ::exam::mySer > {
  static const char* value()
  {
    return "exam/mySer";
  }

  static const char* value(const ::exam::mySer&) { return value(); }
};


// service_traits::MD5Sum< ::exam::mySerRequest> should match
// service_traits::MD5Sum< ::exam::mySer >
template<>
struct MD5Sum< ::exam::mySerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::exam::mySer >::value();
  }
  static const char* value(const ::exam::mySerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::exam::mySerRequest> should match
// service_traits::DataType< ::exam::mySer >
template<>
struct DataType< ::exam::mySerRequest>
{
  static const char* value()
  {
    return DataType< ::exam::mySer >::value();
  }
  static const char* value(const ::exam::mySerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::exam::mySerResponse> should match
// service_traits::MD5Sum< ::exam::mySer >
template<>
struct MD5Sum< ::exam::mySerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::exam::mySer >::value();
  }
  static const char* value(const ::exam::mySerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::exam::mySerResponse> should match
// service_traits::DataType< ::exam::mySer >
template<>
struct DataType< ::exam::mySerResponse>
{
  static const char* value()
  {
    return DataType< ::exam::mySer >::value();
  }
  static const char* value(const ::exam::mySerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EXAM_MESSAGE_MYSER_H
