// Generated by gencpp from file exam/mySerRequest.msg
// DO NOT EDIT!


#ifndef EXAM_MESSAGE_MYSERREQUEST_H
#define EXAM_MESSAGE_MYSERREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace exam
{
template <class ContainerAllocator>
struct mySerRequest_
{
  typedef mySerRequest_<ContainerAllocator> Type;

  mySerRequest_()
    : angle1(0.0)
    , angle2(0.0)
    , angle3(0.0)
    , angle4(0.0)
    , time(0.0)  {
    }
  mySerRequest_(const ContainerAllocator& _alloc)
    : angle1(0.0)
    , angle2(0.0)
    , angle3(0.0)
    , angle4(0.0)
    , time(0.0)  {
  (void)_alloc;
    }



   typedef double _angle1_type;
  _angle1_type angle1;

   typedef double _angle2_type;
  _angle2_type angle2;

   typedef double _angle3_type;
  _angle3_type angle3;

   typedef double _angle4_type;
  _angle4_type angle4;

   typedef double _time_type;
  _time_type time;





  typedef boost::shared_ptr< ::exam::mySerRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::exam::mySerRequest_<ContainerAllocator> const> ConstPtr;

}; // struct mySerRequest_

typedef ::exam::mySerRequest_<std::allocator<void> > mySerRequest;

typedef boost::shared_ptr< ::exam::mySerRequest > mySerRequestPtr;
typedef boost::shared_ptr< ::exam::mySerRequest const> mySerRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::exam::mySerRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::exam::mySerRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::exam::mySerRequest_<ContainerAllocator1> & lhs, const ::exam::mySerRequest_<ContainerAllocator2> & rhs)
{
  return lhs.angle1 == rhs.angle1 &&
    lhs.angle2 == rhs.angle2 &&
    lhs.angle3 == rhs.angle3 &&
    lhs.angle4 == rhs.angle4 &&
    lhs.time == rhs.time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::exam::mySerRequest_<ContainerAllocator1> & lhs, const ::exam::mySerRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace exam

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::exam::mySerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exam::mySerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exam::mySerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exam::mySerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exam::mySerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exam::mySerRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::exam::mySerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a7ba6d783e8cdda9b7155099d049aa3a";
  }

  static const char* value(const ::exam::mySerRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa7ba6d783e8cdda9ULL;
  static const uint64_t static_value2 = 0xb7155099d049aa3aULL;
};

template<class ContainerAllocator>
struct DataType< ::exam::mySerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "exam/mySerRequest";
  }

  static const char* value(const ::exam::mySerRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::exam::mySerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 angle1\n"
"float64 angle2\n"
"float64 angle3\n"
"float64 angle4\n"
"float64 time\n"
;
  }

  static const char* value(const ::exam::mySerRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::exam::mySerRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle1);
      stream.next(m.angle2);
      stream.next(m.angle3);
      stream.next(m.angle4);
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mySerRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::exam::mySerRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::exam::mySerRequest_<ContainerAllocator>& v)
  {
    s << indent << "angle1: ";
    Printer<double>::stream(s, indent + "  ", v.angle1);
    s << indent << "angle2: ";
    Printer<double>::stream(s, indent + "  ", v.angle2);
    s << indent << "angle3: ";
    Printer<double>::stream(s, indent + "  ", v.angle3);
    s << indent << "angle4: ";
    Printer<double>::stream(s, indent + "  ", v.angle4);
    s << indent << "time: ";
    Printer<double>::stream(s, indent + "  ", v.time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXAM_MESSAGE_MYSERREQUEST_H
