// Generated by gencpp from file exam/mySerResponse.msg
// DO NOT EDIT!


#ifndef EXAM_MESSAGE_MYSERRESPONSE_H
#define EXAM_MESSAGE_MYSERRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace exam
{
template <class ContainerAllocator>
struct mySerResponse_
{
  typedef mySerResponse_<ContainerAllocator> Type;

  mySerResponse_()
    : response(false)  {
    }
  mySerResponse_(const ContainerAllocator& _alloc)
    : response(false)  {
  (void)_alloc;
    }



   typedef uint8_t _response_type;
  _response_type response;





  typedef boost::shared_ptr< ::exam::mySerResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::exam::mySerResponse_<ContainerAllocator> const> ConstPtr;

}; // struct mySerResponse_

typedef ::exam::mySerResponse_<std::allocator<void> > mySerResponse;

typedef boost::shared_ptr< ::exam::mySerResponse > mySerResponsePtr;
typedef boost::shared_ptr< ::exam::mySerResponse const> mySerResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::exam::mySerResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::exam::mySerResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::exam::mySerResponse_<ContainerAllocator1> & lhs, const ::exam::mySerResponse_<ContainerAllocator2> & rhs)
{
  return lhs.response == rhs.response;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::exam::mySerResponse_<ContainerAllocator1> & lhs, const ::exam::mySerResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace exam

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::exam::mySerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exam::mySerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exam::mySerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exam::mySerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exam::mySerResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exam::mySerResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::exam::mySerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "003b81baa95ab323fc1ddf3c7d0bee81";
  }

  static const char* value(const ::exam::mySerResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x003b81baa95ab323ULL;
  static const uint64_t static_value2 = 0xfc1ddf3c7d0bee81ULL;
};

template<class ContainerAllocator>
struct DataType< ::exam::mySerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "exam/mySerResponse";
  }

  static const char* value(const ::exam::mySerResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::exam::mySerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool response\n"
"\n"
;
  }

  static const char* value(const ::exam::mySerResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::exam::mySerResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mySerResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::exam::mySerResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::exam::mySerResponse_<ContainerAllocator>& v)
  {
    s << indent << "response: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXAM_MESSAGE_MYSERRESPONSE_H
