// Generated by gencpp from file calculator/cal.msg
// DO NOT EDIT!


#ifndef CALCULATOR_MESSAGE_CAL_H
#define CALCULATOR_MESSAGE_CAL_H

#include <ros/service_traits.h>


#include <calculator/calRequest.h>
#include <calculator/calResponse.h>


namespace calculator
{

struct cal
{

typedef calRequest Request;
typedef calResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct cal
} // namespace calculator


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::calculator::cal > {
  static const char* value()
  {
    return "f44d590eccac8479acf5b93bee12375b";
  }

  static const char* value(const ::calculator::cal&) { return value(); }
};

template<>
struct DataType< ::calculator::cal > {
  static const char* value()
  {
    return "calculator/cal";
  }

  static const char* value(const ::calculator::cal&) { return value(); }
};


// service_traits::MD5Sum< ::calculator::calRequest> should match
// service_traits::MD5Sum< ::calculator::cal >
template<>
struct MD5Sum< ::calculator::calRequest>
{
  static const char* value()
  {
    return MD5Sum< ::calculator::cal >::value();
  }
  static const char* value(const ::calculator::calRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::calculator::calRequest> should match
// service_traits::DataType< ::calculator::cal >
template<>
struct DataType< ::calculator::calRequest>
{
  static const char* value()
  {
    return DataType< ::calculator::cal >::value();
  }
  static const char* value(const ::calculator::calRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::calculator::calResponse> should match
// service_traits::MD5Sum< ::calculator::cal >
template<>
struct MD5Sum< ::calculator::calResponse>
{
  static const char* value()
  {
    return MD5Sum< ::calculator::cal >::value();
  }
  static const char* value(const ::calculator::calResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::calculator::calResponse> should match
// service_traits::DataType< ::calculator::cal >
template<>
struct DataType< ::calculator::calResponse>
{
  static const char* value()
  {
    return DataType< ::calculator::cal >::value();
  }
  static const char* value(const ::calculator::calResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CALCULATOR_MESSAGE_CAL_H
