// Generated by gencpp from file calculator/calRequest.msg
// DO NOT EDIT!


#ifndef CALCULATOR_MESSAGE_CALREQUEST_H
#define CALCULATOR_MESSAGE_CALREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace calculator
{
template <class ContainerAllocator>
struct calRequest_
{
  typedef calRequest_<ContainerAllocator> Type;

  calRequest_()
    : a(0.0)
    , b(0.0)
    , op()  {
    }
  calRequest_(const ContainerAllocator& _alloc)
    : a(0.0)
    , b(0.0)
    , op(_alloc)  {
  (void)_alloc;
    }



   typedef double _a_type;
  _a_type a;

   typedef double _b_type;
  _b_type b;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _op_type;
  _op_type op;





  typedef boost::shared_ptr< ::calculator::calRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::calculator::calRequest_<ContainerAllocator> const> ConstPtr;

}; // struct calRequest_

typedef ::calculator::calRequest_<std::allocator<void> > calRequest;

typedef boost::shared_ptr< ::calculator::calRequest > calRequestPtr;
typedef boost::shared_ptr< ::calculator::calRequest const> calRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::calculator::calRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::calculator::calRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::calculator::calRequest_<ContainerAllocator1> & lhs, const ::calculator::calRequest_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a &&
    lhs.b == rhs.b &&
    lhs.op == rhs.op;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::calculator::calRequest_<ContainerAllocator1> & lhs, const ::calculator::calRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace calculator

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::calculator::calRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::calculator::calRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::calculator::calRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::calculator::calRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::calculator::calRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::calculator::calRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::calculator::calRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c39f692aae57e32e2fe4bae7149f5c06";
  }

  static const char* value(const ::calculator::calRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc39f692aae57e32eULL;
  static const uint64_t static_value2 = 0x2fe4bae7149f5c06ULL;
};

template<class ContainerAllocator>
struct DataType< ::calculator::calRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "calculator/calRequest";
  }

  static const char* value(const ::calculator::calRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::calculator::calRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 a\n"
"float64 b\n"
"string op\n"
;
  }

  static const char* value(const ::calculator::calRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::calculator::calRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
      stream.next(m.op);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct calRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::calculator::calRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::calculator::calRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<double>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<double>::stream(s, indent + "  ", v.b);
    s << indent << "op: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.op);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CALCULATOR_MESSAGE_CALREQUEST_H
